#!/bin/bash
#
#
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/xcat/bin:/opt/xcat/sbin

rm /tmp/ipmi_event_node
rm -rf /tmp/list_ipmi_ip


sqlite3=`which sqlite3`
DB_FILE=~/test.db
SQLITE_OPTIONS=" -column -header  "
 
$sqlite3 $DB_FILE  "
        create table IF NOT EXISTS  test (
		node TEXT NOT NULL,
		dat TEXT NOT NULL,
		taim TEXT NOT NULL,
                event TEXT NOT NULL,
		CONSTRAINT con_primary_name PRIMARY KEY(node,dat,event));"

tabdump ipmi | cut -f 1 -d , -s | sed 's/\"//g' |  sed '1d' | sort > /tmp/list_ipmi_ip


for event_node in $(cat /tmp/list_ipmi_ip )

do
reventlog $event_node >> /tmp/ipmi_event_node
done

while read LINE
do
node=$(echo "$LINE" | awk '{print $1}'| sed 's/\://g'  )
dat2=$(echo "$LINE"  | awk '{print $2}' )
#dat=$(echo "$LINE"  | awk '{print $2}' | date -d  +%Y-%m-%d )
dat=$(date -d "$dat2" +%Y-%m-%d)
taim=$(echo "$LINE" | awk '{print $3}' )
event=$(echo "$LINE"  |  awk '{out=""; for(i=4;i<=NF;i++){out=out" "$i}; print out}' )




$sqlite3 $DB_FILE  " insert into test (node,dat,taim,event) values  ('$node', '$dat', '$taim','$event')"
echo $error
echo $dat2
#echo $LINE
#echo $node

done < /tmp/ipmi_event_node


#for ipmi_node in $(cat /tmp/list_ipmi_ip)

#do 
#node=$(reventlog $ipmi_node 1 | awk '{print $1}'| sed 's/\://g'  )
#dat=$(reventlog $ipmi_node 1 | awk '{print $2}' )
#taim=$(reventlog $ipmi_node 1 | awk '{print $3}' )
#event=$(reventlog $ipmi_node 1  |  awk '{out=""; for(i=4;i<=NF;i++){out=out" "$i}; print out}' )

#echo $node
#echo $dat
#echo $taim
#echo $event

#echo "$rand"

#        $sqlite3 $DB_FILE  " insert into test (node,dat,taim,event) values  ('$node', '$dat', '$taim','$event')"
#        echo $error
 
#done

echo "Уже было внесено:"
$sqlite3 $SQLITE_OPTIONS $DB_FILE <<EOF
        SELECT * FROM test;
EOF

rm -rf /tmp/list_ipmi_ip

 
exit 0

